services:
  portainer:
    image: portainer/portainer-ee:lts
    container_name: portainer
    restart: always
    security_opt:
      - "apparmor:unconfined"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/portainer:/data
    networks:
      - portainer_network

networks:
  portainer_network:
    driver: bridge
    name: portainer_network
    ipam:
      driver: default
      config:
        - subnet: ${PORTAINER_NETWORK_SUBNET:-172.23.0.0/24}