version: '3.8'

services:
  # VictoriaMetrics - Time-series database for metrics
  victoriametrics:
    image: victoriametrics/victoria-metrics:latest
    container_name: victoriametrics
    restart: unless-stopped
    ports:
      - "8428:8428"  # HTTP API and Web UI (vmui)
      - "8089:8089"  # InfluxDB HTTP API (for Home Assistant)
      - "8089:8089/udp"  # InfluxDB UDP API
    volumes:
      - /data/victoriametrics:/victoria-metrics-data
    command:
      - "--storageDataPath=/victoria-metrics-data"              # Path to store time-series data
      - "--httpListenAddr=:8428"                                # HTTP API and Web UI (vmui) port
      - "--influxListenAddr=:8089"                              # Enable InfluxDB protocol for Home Assistant
      - "--retentionPeriod=5y"                                  # Keep metrics for 5 years (Home Assistant historical data)
      - "--dedup.minScrapeInterval=15s"                         # Deduplicate metrics within 15s window (smooths HA transients)
      - "--maxLabelsPerTimeseries=50"                           # Maximum labels per metric (prevents cardinality explosion)
      - "--search.maxQueryDuration=30s"                         # Query timeout (prevents long-running queries)
      - "--search.maxConcurrentRequests=12"                     # Max parallel queries (prevents overload)
      - "--memory.allowedPercent=40"                            # Use 40% of available RAM (leaves room for OS page cache)
      - "--httpAuth.username=${VM_AUTH_USERNAME:-}"             # Optional: HTTP Basic Auth username (empty = disabled)
      - "--httpAuth.password=${VM_AUTH_PASSWORD:-}"             # Optional: HTTP Basic Auth password (empty = disabled)
    environment:
      TZ: ${TIMEZONE:-UTC}
    deploy:
      resources:
        limits:
          memory: ${VM_MEMORY_LIMIT:-2G}  # Prevent OOM crashes
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8428/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - observability
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # VictoriaLogs - High-performance log aggregation
  victorialogs:
    image: victoriametrics/victoria-logs:latest
    container_name: victorialogs
    restart: unless-stopped
    ports:
      - "9428:9428"  # HTTP API and Web UI (select/vmui)
    volumes:
      - /data/victorialogs:/victoria-logs-data
    command:
      - "--storageDataPath=/victoria-logs-data"                # Path to store log data
      - "--httpListenAddr=:9428"                                # HTTP API and Web UI (select/vmui) port
      - "--retentionPeriod=90d"                                 # Keep logs for 90 days (use time-based retention)
      - "--httpAuth.username=${VL_AUTH_USERNAME:-}"             # Optional: HTTP Basic Auth username (empty = disabled)
      - "--httpAuth.password=${VL_AUTH_PASSWORD:-}"             # Optional: HTTP Basic Auth password (empty = disabled)
    environment:
      TZ: ${TIMEZONE:-UTC}
    deploy:
      resources:
        limits:
          memory: ${VL_MEMORY_LIMIT:-1G}  # Prevent OOM crashes
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9428/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - observability
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  # Vector - High-performance log collection and routing
  vector:
    image: timberio/vector:latest-distroless-static  # Smallest, most secure (20-30MB)
    container_name: vector
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8686:8686"  # Vector GraphQL API for monitoring and debugging
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /data/vector/vector.yaml:/etc/vector/vector.yaml:ro     # Vector configuration file
      - /var/log:/var/log:ro
    command: --config /etc/vector/vector.yaml
    environment:
      TZ: ${TIMEZONE:-UTC}
      VL_AUTH_USERNAME: ${VL_AUTH_USERNAME:-}
      VL_AUTH_PASSWORD: ${VL_AUTH_PASSWORD:-}
    deploy:
      resources:
        limits:
          memory: ${VECTOR_MEMORY_LIMIT:-512M}  # Prevent OOM crashes
    networks:
      - observability
    depends_on:
      victorialogs:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # System and network metrics collection
  telegraf:
    image: telegraf:latest
    container_name: telegraf
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    user: "telegraf:${DOCKER_GID:-996}"  # Run as telegraf user with docker group
    volumes:
      - /data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc:/host/etc:ro
    environment:
      HOST_PROC: /host/proc
      HOST_SYS: /host/sys
      HOST_ETC: /host/etc
      TZ: ${TIMEZONE:-UTC}
      VM_AUTH_USERNAME: ${VM_AUTH_USERNAME:-}  # VictoriaMetrics auth (if enabled)
      VM_AUTH_PASSWORD: ${VM_AUTH_PASSWORD:-}
    deploy:
      resources:
        limits:
          memory: ${TELEGRAF_MEMORY_LIMIT:-256M}  # Prevent OOM crashes
    networks:
      - observability
    depends_on:
      victoriametrics:
        condition: service_healthy
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Unified visualization for everything
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"  # Grafana Web UI
    volumes:
      - /data/grafana/data:/var/lib/grafana                              # Persistent data (dashboards, users, etc.)
      - /data/grafana/config/grafana.ini:/etc/grafana/grafana.ini:ro    # Custom Grafana configuration
      - /data/grafana/dashboards:/var/lib/grafana/dashboards:ro         # Dashboard JSON files (auto-loaded)
      - /data/grafana/provisioning:/etc/grafana/provisioning:ro         # Datasource/dashboard provisioning
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}                            # Admin username from .env
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}                    # Admin password from .env
      GF_USERS_ALLOW_SIGN_UP: false                                      # Disable self-registration
      GF_PLUGINS_PREINSTALL: victoriametrics-logs-datasource             # Auto-install VictoriaLogs datasource plugin
      TZ: ${TIMEZONE:-UTC}                                               # Timezone for log timestamps
      GF_LOG_LEVEL: info
      GF_SERVER_ROOT_URL: ${GRAFANA_ROOT_URL}
      GF_SERVER_DOMAIN: ${GRAFANA_DOMAIN}
      GF_SECURITY_COOKIE_SECURE: true
    deploy:
      resources:
        limits:
          memory: ${GRAFANA_MEMORY_LIMIT:-1G}  # Prevent OOM crashes
    networks:
      - observability
    depends_on:
      victoriametrics:
        condition: service_healthy
      victorialogs:
        condition: service_healthy
      telegraf:
        condition: service_started
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

networks:
  observability:
    driver: bridge
    name: observability_network