version: '3.8'

services:
  portainer:
    image: portainer/portainer-ee:lts
    container_name: portainer
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - portainer_network

volumes:
  portainer_data:
    external: true

networks:
  portainer_network:
    driver: bridge
    name: portainer_network
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/24
          gateway: 172.23.0.1