---
- name: Reload udev rules
  ansible.builtin.shell: udevadm control --reload-rules && udevadm trigger
  changed_when: true
  listen: reload-udev

- name: Remove Proxmox subscription nag
  ansible.builtin.command: /usr/local/bin/remove-proxmox-nag.sh
  changed_when: true
  listen: remove-proxmox-nag

- name: Reload AppArmor dhclient profile
  ansible.builtin.command: apparmor_parser -r /etc/apparmor.d/usr.sbin.dhclient
  changed_when: true
  listen: reload-apparmor-dhclient
