# docker-compose-joplin.yml
version: '3.8'

services:
  joplin-server:
    image: joplin/server:latest
    container_name: joplin-server
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "22300:22300"
    environment:
      APP_PORT: 22300
      APP_BASE_URL: ${APP_BASE_URL}
      DB_CLIENT: pg
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE:-joplin}
      POSTGRES_USER: ${POSTGRES_USER:-joplin_user}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      # PostgreSQL 17 specific optimizations
      POSTGRES_CONNECTION_POOL_MIN: 0
      POSTGRES_CONNECTION_POOL_MAX: 10

      # Gmail SMTP Configuration
      MAILER_ENABLED: 1
      MAILER_HOST: smtp.gmail.com
      MAILER_PORT: 587
      MAILER_SECURITY: starttls
      MAILER_AUTH_USER: ${GMAIL_EMAIL}
      MAILER_AUTH_PASSWORD: ${GMAIL_APP_PASSWORD}
      MAILER_NOREPLY_NAME: "Joplin Server"
      MAILER_NOREPLY_EMAIL: ${GMAIL_EMAIL}

      # Optional: Email verification settings
      SIGNUP_ENABLED: 1
      USER_EMAIL_VERIFICATION_ENABLED: 1

      # Filesystem storage configuration
      # Instead of storing everything in PosgreSQL, I use more efficient filesystem storage
      STORAGE_DRIVER: "Type=Filesystem; Path=/data"
      STORAGE_DRIVER_FALLBACK: "Type=Database; Mode=ReadAndClear"

    volumes:
      - /data/joplin:/data

    networks:
      - postgres_network

    healthcheck:
      test: ["CMD-SHELL", "node -e \"require('net').createConnection(22300, 'localhost').on('connect', () => process.exit(0)).on('error', () => process.exit(1))\""]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 240s

networks:
  postgres_network:
    external: true